version: '3.9'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - redis-data:/data
  backend:
    build:
      context: ./url-shortener-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:8000
      - RATE_LIMIT=5
      - REDIS_URL=redis://redis:6379/0
      - TTL=86400
      - REDIS_RECONNECT_ATTEMPTS=5
      - REDIS_RECONNECT_DELAY=1000
      - LOG_LEVEL=info
    ports: ['8000:8000']
    depends_on:
      redis:
        condition: service_healthy
volumes:
  redis-data:
    driver: local