version: '3.9'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
  backend:
    build:
      context: ./url-shortener-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BASE_URL=http://localhost:8000
      - RATE_LIMIT=5
      - REDIS_URL=redis://redis:6379/0
      - TTL=86400
    ports: ['8000:8000']
    depends_on:
      - redis